-- 02_create_tables.sql
USE DATABASE NHS_DEMO;
USE SCHEMA AE;

-- RAW table: intentionally allows dirty data
CREATE OR REPLACE TABLE AE_ATTENDANCE_RAW (
  ATTENDANCE_ID            STRING,
  NHS_NUMBER               STRING,
  HOSPITAL_SITE_CODE       STRING,
  TRUST_CODE               STRING,
  PATIENT_DOB              DATE,
  PATIENT_AGE              NUMBER(3,0),
  PATIENT_GENDER           STRING,         -- Expecting: M/F/U (but we inject issues)
  PATIENT_POSTCODE         STRING,         -- UK postcode (we inject invalid)
  ARRIVAL_TS               TIMESTAMP_NTZ,
  TRIAGE_TS                TIMESTAMP_NTZ,
  FIRST_CLINICIAN_TS       TIMESTAMP_NTZ,
  DISCHARGE_TS             TIMESTAMP_NTZ,
  ARRIVAL_MODE             STRING,         -- Walk-in / Ambulance / Other (we inject invalid)
  CHIEF_COMPLAINT          STRING,
  DIAGNOSIS_CODE           STRING,
  DIAGNOSIS_DESC           STRING,
  WAIT_MINS_TO_TRIAGE      NUMBER(6,0),
  WAIT_MINS_TO_CLINICIAN   NUMBER(6,0),
  TOTAL_LOS_MINS           NUMBER(6,0),
  FOUR_HOUR_BREACH_FLAG    STRING,         -- Y/N (we inject invalid)
  CREATED_AT               TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Quality issue output table (one row per flagged issue)
CREATE OR REPLACE TABLE AE_ATTENDANCE_DQ_ISSUES (
  ATTENDANCE_ID   STRING,
  ISSUE_TYPE      STRING,
  ISSUE_DETAIL    STRING,
  ISSUE_SEVERITY  STRING,   -- INFO/WARN/ERROR
  DETECTED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Cleaned table (simple demo rules; not a full NHS data model)
CREATE OR REPLACE TABLE AE_ATTENDANCE_CLEAN AS
SELECT
  CAST(NULL AS STRING) AS ATTENDANCE_ID,
  CAST(NULL AS STRING) AS NHS_NUMBER,
  CAST(NULL AS STRING) AS HOSPITAL_SITE_CODE,
  CAST(NULL AS STRING) AS TRUST_CODE,
  CAST(NULL AS DATE)   AS PATIENT_DOB,
  CAST(NULL AS NUMBER(3,0)) AS PATIENT_AGE,
  CAST(NULL AS STRING) AS PATIENT_GENDER,
  CAST(NULL AS STRING) AS PATIENT_POSTCODE,
  CAST(NULL AS TIMESTAMP_NTZ) AS ARRIVAL_TS,
  CAST(NULL AS TIMESTAMP_NTZ) AS TRIAGE_TS,
  CAST(NULL AS TIMESTAMP_NTZ) AS FIRST_CLINICIAN_TS,
  CAST(NULL AS TIMESTAMP_NTZ) AS DISCHARGE_TS,
  CAST(NULL AS STRING) AS ARRIVAL_MODE,
  CAST(NULL AS STRING) AS CHIEF_COMPLAINT,
  CAST(NULL AS STRING) AS DIAGNOSIS_CODE,
  CAST(NULL AS STRING) AS DIAGNOSIS_DESC,
  CAST(NULL AS NUMBER(6,0)) AS WAIT_MINS_TO_TRIAGE,
  CAST(NULL AS NUMBER(6,0)) AS WAIT_MINS_TO_CLINICIAN,
  CAST(NULL AS NUMBER(6,0)) AS TOTAL_LOS_MINS,
  CAST(NULL AS STRING) AS FOUR_HOUR_BREACH_FLAG
WHERE 1=0;
