-- 04_data_quality_rules_and_outputs.sql
-- Flags common NHS-ish A&E data quality problems and produces CLEAN table.

USE DATABASE NHS_DEMO;
USE SCHEMA AE;

TRUNCATE TABLE AE_ATTENDANCE_DQ_ISSUES;

-- 1) Missing or malformed identifiers
INSERT INTO AE_ATTENDANCE_DQ_ISSUES (ATTENDANCE_ID, ISSUE_TYPE, ISSUE_DETAIL, ISSUE_SEVERITY)
SELECT ATTENDANCE_ID, 'NHS_NUMBER_NULL', 'NHS_NUMBER is NULL', 'ERROR'
FROM AE_ATTENDANCE_RAW
WHERE NHS_NUMBER IS NULL;

INSERT INTO AE_ATTENDANCE_DQ_ISSUES (ATTENDANCE_ID, ISSUE_TYPE, ISSUE_DETAIL, ISSUE_SEVERITY)
SELECT ATTENDANCE_ID, 'NHS_NUMBER_BAD_FORMAT', 'NHS_NUMBER should be 10 digits', 'ERROR'
FROM AE_ATTENDANCE_RAW
WHERE NHS_NUMBER IS NOT NULL AND NOT REGEXP_LIKE(NHS_NUMBER, '^[0-9]{10}$');

-- 2) Duplicated attendance IDs
INSERT INTO AE_ATTENDANCE_DQ_ISSUES (ATTENDANCE_ID, ISSUE_TYPE, ISSUE_DETAIL, ISSUE_SEVERITY)
SELECT ATTENDANCE_ID, 'DUPLICATE_ATTENDANCE_ID', 'ATTENDANCE_ID occurs more than once', 'ERROR'
FROM AE_ATTENDANCE_RAW
QUALIFY COUNT(*) OVER (PARTITION BY ATTENDANCE_ID) > 1;

-- 3) Demographics validity
INSERT INTO AE_ATTENDANCE_DQ_ISSUES (ATTENDANCE_ID, ISSUE_TYPE, ISSUE_DETAIL, ISSUE_SEVERITY)
SELECT ATTENDANCE_ID, 'DOB_IN_FUTURE', 'PATIENT_DOB is in the future', 'ERROR'
FROM AE_ATTENDANCE_RAW
WHERE PATIENT_DOB > CURRENT_DATE();

INSERT INTO AE_ATTENDANCE_DQ_ISSUES (ATTENDANCE_ID, ISSUE_TYPE, ISSUE_DETAIL, ISSUE_SEVERITY)
SELECT ATTENDANCE_ID, 'AGE_OUT_OF_RANGE', 'PATIENT_AGE is outside expected range 0..120', 'ERROR'
FROM AE_ATTENDANCE_RAW
WHERE PATIENT_AGE IS NULL OR PATIENT_AGE < 0 OR PATIENT_AGE > 120;

INSERT INTO AE_ATTENDANCE_DQ_ISSUES (ATTENDANCE_ID, ISSUE_TYPE, ISSUE_DETAIL, ISSUE_SEVERITY)
SELECT ATTENDANCE_ID, 'GENDER_INVALID', 'PATIENT_GENDER should be M/F/U', 'WARN'
FROM AE_ATTENDANCE_RAW
WHERE PATIENT_GENDER IS NULL OR PATIENT_GENDER NOT IN ('M','F','U');

-- 4) Location validity (very simplified postcode check)
INSERT INTO AE_ATTENDANCE_DQ_ISSUES (ATTENDANCE_ID, ISSUE_TYPE, ISSUE_DETAIL, ISSUE_SEVERITY)
SELECT ATTENDANCE_ID, 'POSTCODE_INVALID', 'PATIENT_POSTCODE fails basic UK postcode pattern', 'WARN'
FROM AE_ATTENDANCE_RAW
WHERE PATIENT_POSTCODE IS NULL
   OR NOT REGEXP_LIKE(UPPER(PATIENT_POSTCODE),
        '^[A-Z]{1,2}[0-9][0-9A-Z]?\s?[0-9][A-Z]{2}$');

-- 5) Timeline validity
INSERT INTO AE_ATTENDANCE_DQ_ISSUES (ATTENDANCE_ID, ISSUE_TYPE, ISSUE_DETAIL, ISSUE_SEVERITY)
SELECT ATTENDANCE_ID, 'ARRIVAL_IN_FUTURE', 'ARRIVAL_TS is in the future', 'ERROR'
FROM AE_ATTENDANCE_RAW
WHERE ARRIVAL_TS > DATEADD('minute', 5, CURRENT_TIMESTAMP());  -- allow a tiny clock skew

INSERT INTO AE_ATTENDANCE_DQ_ISSUES (ATTENDANCE_ID, ISSUE_TYPE, ISSUE_DETAIL, ISSUE_SEVERITY)
SELECT ATTENDANCE_ID, 'TRIAGE_BEFORE_ARRIVAL', 'TRIAGE_TS is before ARRIVAL_TS', 'ERROR'
FROM AE_ATTENDANCE_RAW
WHERE TRIAGE_TS IS NOT NULL AND ARRIVAL_TS IS NOT NULL AND TRIAGE_TS < ARRIVAL_TS;

INSERT INTO AE_ATTENDANCE_DQ_ISSUES (ATTENDANCE_ID, ISSUE_TYPE, ISSUE_DETAIL, ISSUE_SEVERITY)
SELECT ATTENDANCE_ID, 'CLINICIAN_BEFORE_TRIAGE', 'FIRST_CLINICIAN_TS is before TRIAGE_TS', 'ERROR'
FROM AE_ATTENDANCE_RAW
WHERE FIRST_CLINICIAN_TS IS NOT NULL AND TRIAGE_TS IS NOT NULL AND FIRST_CLINICIAN_TS < TRIAGE_TS;

INSERT INTO AE_ATTENDANCE_DQ_ISSUES (ATTENDANCE_ID, ISSUE_TYPE, ISSUE_DETAIL, ISSUE_SEVERITY)
SELECT ATTENDANCE_ID, 'DISCHARGE_MISSING', 'DISCHARGE_TS is NULL', 'WARN'
FROM AE_ATTENDANCE_RAW
WHERE DISCHARGE_TS IS NULL;

INSERT INTO AE_ATTENDANCE_DQ_ISSUES (ATTENDANCE_ID, ISSUE_TYPE, ISSUE_DETAIL, ISSUE_SEVERITY)
SELECT ATTENDANCE_ID, 'DISCHARGE_BEFORE_ARRIVAL', 'DISCHARGE_TS is before ARRIVAL_TS', 'ERROR'
FROM AE_ATTENDANCE_RAW
WHERE DISCHARGE_TS IS NOT NULL AND ARRIVAL_TS IS NOT NULL AND DISCHARGE_TS < ARRIVAL_TS;

-- 6) Duration / wait validity
INSERT INTO AE_ATTENDANCE_DQ_ISSUES (ATTENDANCE_ID, ISSUE_TYPE, ISSUE_DETAIL, ISSUE_SEVERITY)
SELECT ATTENDANCE_ID, 'WAIT_NEGATIVE_TRIAGE', 'WAIT_MINS_TO_TRIAGE is negative', 'ERROR'
FROM AE_ATTENDANCE_RAW
WHERE WAIT_MINS_TO_TRIAGE IS NOT NULL AND WAIT_MINS_TO_TRIAGE < 0;

INSERT INTO AE_ATTENDANCE_DQ_ISSUES (ATTENDANCE_ID, ISSUE_TYPE, ISSUE_DETAIL, ISSUE_SEVERITY)
SELECT ATTENDANCE_ID, 'WAIT_EXTREME_CLINICIAN', 'WAIT_MINS_TO_CLINICIAN is unrealistically high', 'WARN'
FROM AE_ATTENDANCE_RAW
WHERE WAIT_MINS_TO_CLINICIAN IS NOT NULL AND WAIT_MINS_TO_CLINICIAN > 24*60;

INSERT INTO AE_ATTENDANCE_DQ_ISSUES (ATTENDANCE_ID, ISSUE_TYPE, ISSUE_DETAIL, ISSUE_SEVERITY)
SELECT ATTENDANCE_ID, 'LOS_NEGATIVE', 'TOTAL_LOS_MINS is negative', 'ERROR'
FROM AE_ATTENDANCE_RAW
WHERE TOTAL_LOS_MINS IS NOT NULL AND TOTAL_LOS_MINS < 0;

-- 7) Domain validity
INSERT INTO AE_ATTENDANCE_DQ_ISSUES (ATTENDANCE_ID, ISSUE_TYPE, ISSUE_DETAIL, ISSUE_SEVERITY)
SELECT ATTENDANCE_ID, 'ARRIVAL_MODE_INVALID', 'ARRIVAL_MODE should be Walk-in/Ambulance/Other', 'WARN'
FROM AE_ATTENDANCE_RAW
WHERE ARRIVAL_MODE IS NULL OR ARRIVAL_MODE NOT IN ('Walk-in','Ambulance','Other');

INSERT INTO AE_ATTENDANCE_DQ_ISSUES (ATTENDANCE_ID, ISSUE_TYPE, ISSUE_DETAIL, ISSUE_SEVERITY)
SELECT ATTENDANCE_ID, 'BREACH_FLAG_INVALID', 'FOUR_HOUR_BREACH_FLAG should be Y/N', 'WARN'
FROM AE_ATTENDANCE_RAW
WHERE FOUR_HOUR_BREACH_FLAG IS NULL OR FOUR_HOUR_BREACH_FLAG NOT IN ('Y','N');

-- Build CLEAN table:
-- - Keep one record per ATTENDANCE_ID (latest CREATED_AT wins)
-- - Coerce gender invalids to 'U'
-- - Coerce arrival_mode invalids to 'Other'
-- - Null out impossible durations (negative)
-- - Recompute waits and LOS from timestamps when possible
CREATE OR REPLACE TABLE AE_ATTENDANCE_CLEAN AS
WITH dedup AS (
  SELECT *
  FROM AE_ATTENDANCE_RAW
  QUALIFY ROW_NUMBER() OVER (PARTITION BY ATTENDANCE_ID ORDER BY CREATED_AT DESC) = 1
),
fixed AS (
  SELECT
    ATTENDANCE_ID,
    NHS_NUMBER,
    HOSPITAL_SITE_CODE,
    TRUST_CODE,
    PATIENT_DOB,
    IFF(PATIENT_AGE BETWEEN 0 AND 120, PATIENT_AGE, NULL) AS PATIENT_AGE,
    IFF(PATIENT_GENDER IN ('M','F','U'), PATIENT_GENDER, 'U') AS PATIENT_GENDER,
    PATIENT_POSTCODE,
    ARRIVAL_TS,
    TRIAGE_TS,
    FIRST_CLINICIAN_TS,
    DISCHARGE_TS,
    IFF(ARRIVAL_MODE IN ('Walk-in','Ambulance','Other'), ARRIVAL_MODE, 'Other') AS ARRIVAL_MODE,
    CHIEF_COMPLAINT,
    DIAGNOSIS_CODE,
    DIAGNOSIS_DESC,

    -- recompute waits if timestamps present; else keep original if sensible
    COALESCE(
      IFF(ARRIVAL_TS IS NOT NULL AND TRIAGE_TS IS NOT NULL AND TRIAGE_TS >= ARRIVAL_TS,
          DATEDIFF('minute', ARRIVAL_TS, TRIAGE_TS), NULL),
      IFF(WAIT_MINS_TO_TRIAGE >= 0, WAIT_MINS_TO_TRIAGE, NULL)
    ) AS WAIT_MINS_TO_TRIAGE,

    COALESCE(
      IFF(ARRIVAL_TS IS NOT NULL AND FIRST_CLINICIAN_TS IS NOT NULL AND FIRST_CLINICIAN_TS >= ARRIVAL_TS,
          DATEDIFF('minute', ARRIVAL_TS, FIRST_CLINICIAN_TS), NULL),
      IFF(WAIT_MINS_TO_CLINICIAN BETWEEN 0 AND 24*60, WAIT_MINS_TO_CLINICIAN, NULL)
    ) AS WAIT_MINS_TO_CLINICIAN,

    COALESCE(
      IFF(ARRIVAL_TS IS NOT NULL AND DISCHARGE_TS IS NOT NULL AND DISCHARGE_TS >= ARRIVAL_TS,
          DATEDIFF('minute', ARRIVAL_TS, DISCHARGE_TS), NULL),
      IFF(TOTAL_LOS_MINS >= 0, TOTAL_LOS_MINS, NULL)
    ) AS TOTAL_LOS_MINS,

    -- breach flag: recompute if timestamps exist and discharge present
    COALESCE(
      IFF(ARRIVAL_TS IS NOT NULL AND DISCHARGE_TS IS NOT NULL AND DISCHARGE_TS >= ARRIVAL_TS,
          IFF(DATEDIFF('minute', ARRIVAL_TS, DISCHARGE_TS) > 240, 'Y', 'N'), NULL),
      IFF(FOUR_HOUR_BREACH_FLAG IN ('Y','N'), FOUR_HOUR_BREACH_FLAG, NULL)
    ) AS FOUR_HOUR_BREACH_FLAG
  FROM dedup
)
SELECT * FROM fixed;

-- Summaries
SELECT ISSUE_TYPE, ISSUE_SEVERITY, COUNT(*) AS ISSUE_COUNT
FROM AE_ATTENDANCE_DQ_ISSUES
GROUP BY 1,2
ORDER BY ISSUE_COUNT DESC;

SELECT COUNT(*) AS CLEAN_ROWS FROM AE_ATTENDANCE_CLEAN;
